# Generated by Django 2.1.3 on 2018-11-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pic',
            new_name='profile_picture',
        ),
    ]
