# Generated by Django 2.1.3 on 2018-12-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181201_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.OrganizationProfile'),
        ),
    ]
