# Generated by Django 2.1.3 on 2019-02-05 02:59

import applications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('description_text', models.CharField(max_length=300)),
            ],
            bases=(models.Model, applications.models.QuestionSubclass),
        ),
        migrations.CreateModel(
            name='FileSubmitQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('description_text', models.CharField(max_length=300)),
            ],
            bases=(models.Model, applications.models.QuestionSubclass),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('description_text', models.CharField(max_length=300)),
            ],
            bases=(models.Model, applications.models.QuestionSubclass),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=40)),
                ('correct', models.BooleanField(default=False)),
                ('multiple_choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.MultipleChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('FS', 'File Submit'), ('DA', 'Data Entry')], max_length=2)),
                ('order', models.CharField(max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
                ('question_da', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.DataEntryQuestion')),
                ('question_fs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.FileSubmitQuestion')),
                ('question_mc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.MultipleChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('description_text', models.CharField(max_length=300)),
            ],
            bases=(models.Model, applications.models.QuestionSubclass),
        ),
        migrations.AddField(
            model_name='question',
            name='question_sa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.ShortAnswerQuestion'),
        ),
    ]
