# Generated by Django 2.1.3 on 2019-02-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestionoption',
            name='list_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_da',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.DataEntryQuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_fs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.FileSubmitQuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_mc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.MultipleChoiceQuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_sa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.ShortAnswerQuestion'),
        ),
    ]
