# Generated by Django 2.1.3 on 2019-02-08 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_auto_20190205_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_answer', models.IntegerField(default=0)),
                ('sa_answer', models.CharField(default='', max_length=1000)),
                ('da_answer', models.CharField(default='', max_length=80)),
                ('fs_answer', models.FileField(null=True, upload_to='answers')),
                ('application_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationResponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Question')),
            ],
        ),
    ]
